audits/urls.py
# from django.conf.urls import url
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from repository.views.base import RepoCopyView
from . import views
from .views import RepoCopy, AuditCopyPushRepo, AuditCopyView

urlpatterns = [
    path('', login_required(views.IndexView.as_view()), name='index'),
    path('create/', login_required(views.audit_create), name='audit_create'),
    path('audit/<int:audit_id>/copy-audit/', login_required(
        AuditCopyView.as_view()), name='audit_copy'),
    path('audit/<int:audit_id>/copy-repo/', login_required(
        RepoCopyView.as_view()), name='repo_copy'),
    path('audit/<int:audit_id>/copy-repos/', login_required(
        RepoCopy.as_view()), name='repo_copy_view'),
    path('audit/<int:audit_id>/push-repo/', login_required(
        AuditCopyPushRepo.as_view()), name='audit_push_repo'),

    path('audit/<int:audit_id>/', login_required(views.audit), name='audit'),
    path('not_implemented', login_required(views.not_implemented), name='not_implemented'),

    # path('audit/process/create/', login_required(views.process),
    #     name='process_create'),
    # path('audit/process/<int:process_id>/',
    #     login_required(views.process), name='audit_process'),
    # path('audit/objective/create/', login_required(views.objective),
    #     name='objective_create'),
    # path('audit/objective/<int:objective_id>/',
    #     login_required(views.objective), name='audit_objective'),
    # path('audit/risk/create/', login_required(views.risk), name='risk_create'),
    # path('audit/risk/<int:risk_id>/', login_required(views.risk),
    #     name='audit_risk'),
    # path('audit/<int:audit_id>/control/create/',
    #     login_required(views.control_create), name='control_create'),
    # path('audit/control/<int:control_id>/',
    #     login_required(views.control), name='audit_control'),

    path('audit/<int:audit_id>/execute/<str:view_type>', #process|objective|risk|control|test
        login_required(views.AuditExecuteView.as_view()), name='audit_execute'),
    path('audit/process/<int:process_id>/objective/', login_required(views.process_objective),
        name='audit_process_objective'),
    path('audit/objective/<int:objective_id>/risks/',
        login_required(views.objective_risk), name='audit_objective_risk'),
    path('audit/risk/<int:risk_id>/controller/',
        login_required(views.risk_controller), name='audit_risk_controller'),
    path('audit/control/<int:control_id>/test/',
        login_required(views.controller_test), name='audit_controller_test'),
    path('audit/test/<int:test_id>/findings/',
        login_required(views.test_findings), name='audit_test_findings'),
    path('audit/test/<int:test_id>/ajax/',
        login_required(views.AjaxTestResultView.as_view()),
        name='audit_ajax_test_form'),
    path('audit/finding/ajax-add/',
        login_required(views.AjaxFindingView.as_view()),
        name='ajax_finding_view'),
    path('attachment/<int:attachment_id>/delete/',
        login_required(views.AjaxAttachmentDeleteView.as_view()),
        name='ajax_attachment_delete'),
    path('audit/<int:audit_id>/management/', login_required(views.AuditChildView.as_view()),
        name='audit_management'),
    # Process Management
    path('audit/<int:audit_id>/process/add/', login_required(views.AjaxProcessAddEditView.as_view()),
        name='ajax_process_add'),
    path('audit/<int:audit_id>/process/<int:process_id>/edit/', login_required(views.AjaxProcessAddEditView.as_view()),
        name='ajax_process_edit'),
    path('process/<int:process_id>/delete/', login_required(views.AjaxProcessDeleteView.as_view()),
        name='ajax_process_delete'),
    # Objective Management
    path('audit/<int:audit_id>/objective/add/', login_required(views.AjaxObjectiveAddEditView.as_view()),
        name='ajax_objective_add'),
    path('audit/<int:audit_id>/objective/<int:objective_id>/edit/', login_required(views.AjaxObjectiveAddEditView.as_view()),
        name='ajax_process_edit'),
    path('objective/<int:objective_id>/delete/', views.AjaxObjectiveDeleteView.as_view(),
        name='ajax_objective_delete'),
    # Risk Management
    path('audit/<int:audit_id>/risk/add/', login_required(views.AjaxRiskAddEditView.as_view()),
        name='ajax_risk_add'),
    path('audit/<int:audit_id>/risk/<int:risk_id>/edit/', login_required(views.AjaxRiskAddEditView.as_view()),
        name='ajax_risk_edit'),
    path('risk/<int:risk_id>/delete/', login_required(views.AjaxRiskDeleteView.as_view()),
        name='ajax_risk_delete'),
    # Control Management
    path('audit/<int:audit_id>/control/add/', login_required(views.AjaxControlAddEditView.as_view()),
        name='ajax_control_add'),
    path('audit/<int:audit_id>/control/<int:control_id>/edit/', login_required(views.AjaxControlAddEditView.as_view()),
        name='ajax_control_edit'),
    path('control/<int:control_id>/delete/', login_required(views.AjaxControlDeleteView.as_view()),
        name='ajax_control_delete'),
    # Test Management
    path('audit/<int:audit_id>/test/add/', login_required(views.AjaxTestAddEditView.as_view()),
        name='ajax_test_add'),
    path('audit/<int:audit_id>/test/<int:test_id>/edit/', login_required(views.AjaxTestAddEditView.as_view()),
        name='ajax_test_edit'),
    path('test/<int:test_id>/delete/', login_required(views.AjaxTestDeleteView.as_view()),
        name='ajax_test_delete'),
    # Report Generation
    path('audit/<int:pk>/report/', login_required(views.AuditReport.as_view()),
        name='audit_report'),
]

envelop/urls.py
"""envelop URL Configuration

"""
from django.conf import settings
# from django.conf.urls import include, urls
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.views.generic import TemplateView
from django.views.static import serve

from audits.views import index, LoginView

admin.site.site_header = 'Envelop administration'
admin.AdminSite.site_title = 'Envelop'

urlpatterns = [
    path('', login_required(index), name='index'),
    path('login/', LoginView.as_view(), name='envelope_login'),
    path('not_implemented/', TemplateView.as_view(template_name="not_implemented.html")),
    path('audits/', include(('audits.urls', 'audits'), namespace="audits")),
    path('admin/', admin.site.urls),
    #    url(r'^files/', include('db_file_storage.urls')),
    path('planning/', include(('planning.urls', 'planning'), namespace='planning')),
    # url('help/', serve, {'document_root': settings.DOCS_ROOT, 'path': 'index.html'}),
    # url('help/(?P<path>.*)$', serve, {'document_root': settings.DOCS_ROOT}),
    path('repository/', include('repository.urls', "repo")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

planning/urls.py
# -*- coding: utf-8 -*-
# from django.conf.urls import url
from django.urls import path, include

from planning.views import PlanningView, PlanningAuditMonthView, PlanningDayView

urlpatterns = [
    path('', PlanningView.as_view(), name="planning_list"),
    path('day/', PlanningDayView.as_view(), name="planning_day"),
    path('audits/', PlanningAuditMonthView.as_view(), name="planning_audits"),
]

planning/models.py
from django.db import models

# Create your models here.

planning/views.py
# -*- coding: utf-8 -*-
import datetime
from dateutil.relativedelta import relativedelta
from django.contrib.auth.models import User
from django.db.models import Count
from django.http import JsonResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.urls import reverse
from django.views import generic
from django.views.decorators.csrf import csrf_exempt

from audits.models import Audit  # , AuditExecute


class PlanningView(generic.View):

    def get(self, request):
        start_day = datetime.datetime.today().date().replace(day=1)
        end_day = datetime.datetime.today().date() + \
                  relativedelta(day=1, months=+1)
        events = Audit.objects.filter(start_date__lte=end_day,
                                      end_date__gte=start_day).extra(select={'start': 'start_date',
                                                                             'end': 'end_date', 'url': 'id', 'status': 'status'}).values('title', 'start', 'end', 'url', 'status')
        for event in events:
            if (event["status"] == "DR"):
                # DRAFT status
                event["backgroundColor"] = "#AAAAAA"
            elif (event["status"] == "AC"):
                # ACTIVE status
                event["backgroundColor"] = "#00BB00"
            elif (event["status"] == "AC"):
                # CLOSED status
                event["backgroundColor"] = "#0000BB"

        return render(request, "planning/list.html",
                      {'events': events})


class PlanningAuditMonthView(generic.View):
    @csrf_exempt
    def get(self, request):
        day = request.GET["day"]
        start_day = datetime.datetime.strptime(day, "%d-%m-%Y").date()
        end_day = start_day + relativedelta(day=1, months=+1)

        events = list(Audit.objects.filter(start_date__lte=end_day,
                                           end_date__gte=start_day).extra(select={'start': 'start_date',
                                                                                  'end': 'end_date', 'audit_id': 'id', 'status': 'status'}).values('title', 'start', 'end', 'id', 'status'))
        for event in events:
            if (event["status"] == "DR"):
                # DRAFT status
                event["backgroundColor"] = "#AAAAAA"
            elif (event["status"] == "AC"):
                # ACTIVE status
                event["backgroundColor"] = "#00BB00"
            elif (event["status"] == "AC"):
                # CLOSED status
                event["backgroundColor"] = "#0000BB"

            event["start"] = event["start"].strftime('%Y-%m-%d')
            event["end"] = event["end"].strftime('%Y-%m-%d 23:59:59')
            event["url"] = reverse('audits:audit', kwargs={'audit_id': event["id"]})

        return JsonResponse({'events': events})


class PlanningDayView(generic.View):
    @csrf_exempt
    def get(self, request):
        data = {}
        day = request.GET["day"]
        selected_day = datetime.datetime.strptime(day, "%d-%m-%Y").date()
        audits_list = Audit.objects.filter(start_date__lte=selected_day,
                                           end_date__gte=selected_day).values_list('id', flat=True)
        print("ok reached")
        execute = AuditExecute.objects.filter(audit_id__in=audits_list) \
            .values('assigned_to__username').annotate(Count('assigned_to'))
        users = []
        for user in execute:
            u = User.objects.get(username=user['assigned_to__username'])
            users.append({'name': u.get_full_name(),
                          'username': user['assigned_to__username'],
                          'count': user['assigned_to__count']})
        data['html'] = render_to_string('planning/users.html',
                                        {'users': users, 'audits_list': audits_list})
        return JsonResponse(data)

planning/templates/planning/list.html
{% extends "base.html" %}
{% load static %}
{% block page_title %}Planning{% endblock %}

{% block header_html %}
    <link rel="stylesheet" href="{% static "css/fullcalendar.min.css" %}">
    <script type="text/javascript" src="{% static "js/moment.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/fullcalendar.min.js" %}"></script>
{% endblock %}

{% block content %}
    {% csrf_token %}
    <div id="page-wrapper"><br/>
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4>Planning</h4>
                        </div>
                        <div class="panel-body" id="calendar">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="popover-head" class="hide">some title</div>
    <div id="popover-content" class="hide">
        <form>
            <input type="text" name="asa" value="asa"/>
        </form>
    </div>
    <div class="modal fade bs-example-modal-sm" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                </div>
                <div class="modal-body" id="modalbody">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script>
        $(document).ready(function () {
            function convertToEvents(events) {
                var convertedEvents = [{% for event in events %}{title: '{{ event.title }}',
                        start: '{{ event.start }}',
                        end: '{{ event.end }}'},{% endfor %}];
                return convertedEvents;
            }

            $('body').on('click', 'button.fc-prev-button', function () {
                var moment = $('#calendar').fullCalendar('getDate');
                var eventDict = {};
                $.ajax({
                    type: 'GET',
                    url: "{% url 'planning:planning_audits' %}?day=" + moment.format('DD-MM-YYYY'),
                    success: function (response) {
                        $('#calendar').fullCalendar('removeEvents');
                        $('#calendar').fullCalendar('addEventSource', response.events);
                        $('#calendar').fullCalendar('rerenderEvents');
                    }
                });
            });

            $('body').on('click', 'button.fc-next-button', function () {
                var moment = $('#calendar').fullCalendar('getDate');
                $.ajax({
                    type: 'GET',
                    url: "{% url 'planning:planning_audits' %}?day=" + moment.format('DD-MM-YYYY'),
                    success: function (response) {
                        $('#calendar').fullCalendar('removeEvents');
                        $('#calendar').fullCalendar('addEventSource', response.events);
                        $('#calendar').fullCalendar('rerenderEvents');
                    }
                });
            });

            var events = [{% for event in events %}{
                    title: '{{ event.title }}',
                    start: '{{ event.start|date:"Y-m-d" }}',
                    end: '{{ event.end|date:"Y-m-d 23:59:59" }}',
                    backgroundColor: '{{ event.backgroundColor }}',
                    url: '{% url 'audits:audit' event.url %}',
                    },
                {% endfor %}];

            $('#calendar').fullCalendar({
                header: {
                    left: 'prev,next',
                    center: 'title',
                    right: 'month'
                },
                defaultDate: new Date(),
                editable: false,
                displayEventEnd: false,
                displayEventTime: false,
                allDay: true,
                eventRender: function (event, element, view) {
                },
                events: events,
                //        dayClick: function (date, allDay, jsEvent, view) {
                //            ShowEventPopup(date);
                //        },
                //        eventClick: function(event) {
                //            if (event.url) {
                //              window.open(event.url);
                //              return false;
                //            }
                //        }
            });

            function ShowEventPopup(date) {
                $('#myModal').modal('toggle');
                $('#myModalLabel').text(date.format('DD MMM YYYY'));
                $.ajax({
                    type: 'GET',
                    url: "{% url 'planning:planning_day' %}?day=" + date.format('DD-MM-YYYY'), success: function (response) {
                        $("#modalbody").html(response.html);
                    }
                });

            }

        });
    </script>
{% endblock %}

planning/templates/planning/users.html
{% if users %}
    {% for user in users %}
        <div class="alert {% if user.count == 1 %}alert-info{% else %}alert-danger{% endif %}" role="alert">
            <strong>{{ user.name }}</strong><small>({{ user.username }})</small> {% if user.count > 1 %}<span class="badge pull-right">{{ user.count }}</span>{% endif %}
        </div>
    {% endfor %}
{% else %}
    <div class="alert alert-warning" role="alert">
        <strong>{% if audits_list %}No Conflicts{% else %}No Audits{% endif %}</strong>
    </div>
{% endif %}