audits/urls.py
# from django.conf.urls import url
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from repository.views.base import RepoCopyView
from . import views
from .views import RepoCopy, AuditCopyPushRepo, AuditCopyView

urlpatterns = [
    path('', login_required(views.IndexView.as_view()), name='index'),
    path('create/', login_required(views.audit_create), name='audit_create'),
    path('audit/<int:audit_id>/copy-audit/', login_required(
        AuditCopyView.as_view()), name='audit_copy'),
    path('audit/<int:audit_id>/copy-repo/', login_required(
        RepoCopyView.as_view()), name='repo_copy'),
    path('audit/<int:audit_id>/copy-repos/', login_required(
        RepoCopy.as_view()), name='repo_copy_view'),
    path('audit/<int:audit_id>/push-repo/', login_required(
        AuditCopyPushRepo.as_view()), name='audit_push_repo'),

    path('audit/<int:audit_id>/', login_required(views.audit), name='audit'),
    path('not_implemented', login_required(views.not_implemented), name='not_implemented'),

    # path('audit/process/create/', login_required(views.process),
    #     name='process_create'),
    # path('audit/process/<int:process_id>/',
    #     login_required(views.process), name='audit_process'),
    # path('audit/objective/create/', login_required(views.objective),
    #     name='objective_create'),
    # path('audit/objective/<int:objective_id>/',
    #     login_required(views.objective), name='audit_objective'),
    # path('audit/risk/create/', login_required(views.risk), name='risk_create'),
    # path('audit/risk/<int:risk_id>/', login_required(views.risk),
    #     name='audit_risk'),
    # path('audit/<int:audit_id>/control/create/',
    #     login_required(views.control_create), name='control_create'),
    # path('audit/control/<int:control_id>/',
    #     login_required(views.control), name='audit_control'),

    path('audit/<int:audit_id>/execute/<str:view_type>', #process|objective|risk|control|test
        login_required(views.AuditExecuteView.as_view()), name='audit_execute'),
    path('audit/process/<int:process_id>/objective/', login_required(views.process_objective),
        name='audit_process_objective'),
    path('audit/objective/<int:objective_id>/risks/',
        login_required(views.objective_risk), name='audit_objective_risk'),
    path('audit/risk/<int:risk_id>/controller/',
        login_required(views.risk_controller), name='audit_risk_controller'),
    path('audit/control/<int:control_id>/test/',
        login_required(views.controller_test), name='audit_controller_test'),
    path('audit/test/<int:test_id>/findings/',
        login_required(views.test_findings), name='audit_test_findings'),
    path('audit/test/<int:test_id>/ajax/',
        login_required(views.AjaxTestResultView.as_view()),
        name='audit_ajax_test_form'),
    path('audit/finding/ajax-add/',
        login_required(views.AjaxFindingView.as_view()),
        name='ajax_finding_view'),
    path('attachment/<int:attachment_id>/delete/',
        login_required(views.AjaxAttachmentDeleteView.as_view()),
        name='ajax_attachment_delete'),
    path('audit/<int:audit_id>/management/', login_required(views.AuditChildView.as_view()),
        name='audit_management'),
    # Process Management
    path('audit/<int:audit_id>/process/add/', login_required(views.AjaxProcessAddEditView.as_view()),
        name='ajax_process_add'),
    path('audit/<int:audit_id>/process/<int:process_id>/edit/', login_required(views.AjaxProcessAddEditView.as_view()),
        name='ajax_process_edit'),
    path('process/<int:process_id>/delete/', login_required(views.AjaxProcessDeleteView.as_view()),
        name='ajax_process_delete'),
    # Objective Management
    path('audit/<int:audit_id>/objective/add/', login_required(views.AjaxObjectiveAddEditView.as_view()),
        name='ajax_objective_add'),
    path('audit/<int:audit_id>/objective/<int:objective_id>/edit/', login_required(views.AjaxObjectiveAddEditView.as_view()),
        name='ajax_process_edit'),
    path('objective/<int:objective_id>/delete/', views.AjaxObjectiveDeleteView.as_view(),
        name='ajax_objective_delete'),
    # Risk Management
    path('audit/<int:audit_id>/risk/add/', login_required(views.AjaxRiskAddEditView.as_view()),
        name='ajax_risk_add'),
    path('audit/<int:audit_id>/risk/<int:risk_id>/edit/', login_required(views.AjaxRiskAddEditView.as_view()),
        name='ajax_risk_edit'),
    path('risk/<int:risk_id>/delete/', login_required(views.AjaxRiskDeleteView.as_view()),
        name='ajax_risk_delete'),
    # Control Management
    path('audit/<int:audit_id>/control/add/', login_required(views.AjaxControlAddEditView.as_view()),
        name='ajax_control_add'),
    path('audit/<int:audit_id>/control/<int:control_id>/edit/', login_required(views.AjaxControlAddEditView.as_view()),
        name='ajax_control_edit'),
    path('control/<int:control_id>/delete/', login_required(views.AjaxControlDeleteView.as_view()),
        name='ajax_control_delete'),
    # Test Management
    path('audit/<int:audit_id>/test/add/', login_required(views.AjaxTestAddEditView.as_view()),
        name='ajax_test_add'),
    path('audit/<int:audit_id>/test/<int:test_id>/edit/', login_required(views.AjaxTestAddEditView.as_view()),
        name='ajax_test_edit'),
    path('test/<int:test_id>/delete/', login_required(views.AjaxTestDeleteView.as_view()),
        name='ajax_test_delete'),
    # Report Generation
    path('audit/<int:pk>/report/', login_required(views.AuditReport.as_view()),
        name='audit_report'),
]

envelop/urls.py
"""envelop URL Configuration

"""
from django.conf import settings
# from django.conf.urls import include, urls
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.views.generic import TemplateView
from django.views.static import serve

from audits.views import index, LoginView

admin.site.site_header = 'Envelop administration'
admin.AdminSite.site_title = 'Envelop'

urlpatterns = [
    path('', login_required(index), name='index'),
    path('login/', LoginView.as_view(), name='envelope_login'),
    path('not_implemented/', TemplateView.as_view(template_name="not_implemented.html")),
    path('audits/', include(('audits.urls', 'audits'), namespace="audits")),
    path('admin/', admin.site.urls),
    #    url(r'^files/', include('db_file_storage.urls')),
    path('planning/', include(('planning.urls', 'planning'), namespace='planning')),
    # url('help/', serve, {'document_root': settings.DOCS_ROOT, 'path': 'index.html'}),
    # url('help/(?P<path>.*)$', serve, {'document_root': settings.DOCS_ROOT}),
    path('repository/', include('repository.urls', "repo")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

repository/urls.py
# from django.conf.urls import url
from django.urls import path
from django.contrib.auth.decorators import login_required
from enum import Enum

from repository.views.base import AjaxAttachmentDeleteView, AjaxChildsAddEditView, AjaxChildsDeleteView, ProcessGroupCreateView, ProcessGroupDetailView, ProcessGroupGetChilds, \
    ProcessGroupManagement, ReposIndexView
from repository.views.wipani import AjaxChildsDetailsView, AjaxWipaniDeleteView, AjaxWipaniPullView, AjaxWipaniPushView, TokenView, RegisterView, WipaniDetailsView, WipaniListView

app_name = "repo"

class ObjType1(Enum):
    PROCESS_GROUP = 'process_group'
    PROCESS = 'process'
    OBJECTIVE = 'objective'
    RISK = 'risk'
    CONTROL = 'control'
    TEST = 'test'

urlpatterns = [
    path('', login_required(ReposIndexView.as_view()), name='repo_index'),
    path('process-group/create/', login_required(ProcessGroupCreateView.as_view()), name='pg_create'),
    path('process-group/<int:process_group_id>/', login_required(ProcessGroupDetailView.as_view()), name='process_group'),
    path('process-group/<int:process_group_id>/management/', login_required(ProcessGroupManagement.as_view()),
        name='pg_management'),
    path('process-group/<int:process_group_id>/management/<str:ctype>process_group|process|objective|risk|control|test)/<int:object_id>/childs/',
        login_required(ProcessGroupGetChilds.as_view()), name='pg_childs'),
    path('process-group/<int:process_group_id>/management/<str:ctype>process_group|process|objective|risk|control|test)/add/',
        login_required(AjaxChildsAddEditView.as_view()), name='pg_childs_add'),
    path('process-group/<int:process_group_id>/management/<str:ctype>process_group|process|objective|risk|control|test)/<int:object_id>/edit/',
        login_required(AjaxChildsAddEditView.as_view()), name='pg_childs_edit'),
    path('process-group/<int:process_group_id>/management/<str:ctype>process_group|process|objective|risk|control|test)/<int:object_id>/delete/',
        login_required(AjaxChildsDeleteView.as_view()), name='pg_childs_delete'),

    path('attachment/<int:attachment_id>/delete/', login_required(AjaxAttachmentDeleteView.as_view()),
        name='ajax_attachment_delete'),

    path('wipani/register/', RegisterView.as_view(), name='WipaniRegister'),
    path('wipani/token/', TokenView.as_view(), name='WipaniToken'),
    path('wipani/list/', WipaniListView.as_view(), name='WipaniList'),
    path('wipani/list/<int:pk>/', WipaniDetailsView.as_view(), name='WipaniDetails'),
    path('wipani/list/<int:pk>/details/', AjaxChildsDetailsView.as_view(), name='AjaxChildsDetails'),
    path('wipani/list/<int:pk>/pull/', AjaxWipaniPullView.as_view(), name='AjaxWipaniPullView'),
    path('wipani/list/<int:pk>/delete/<str:name>/', AjaxWipaniDeleteView.as_view(), name='AjaxWipaniDeleteView'),
    path('process-group/<int:pk>/wipani/push/', AjaxWipaniPushView.as_view(), name='AjaxWipaniPush'),
]

repository/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import gettext

from repository.models import Process_Group, Process, Objective, Risk, Control, Test


class WipaniRegisterForm(forms.ModelForm):
    email = forms.EmailField(
        label='Email',
        required=True,
    )
    first_name = forms.CharField(
        label="First Name",
        required=True,
    )
    last_name = forms.CharField(
        label="Last Name",
        required=True,
    )

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class WipaniTokenForm(forms.Form):
    email = forms.EmailField(
        label="Email",
        required=False,
        widget=forms.EmailInput(attrs={
            'autocapitalize': 'none',
            'autocomplete': 'email',
            'autofocus': True,
            'style': 'width: 300px; padding-left: 8px;'
        }),
    )
    token = forms.CharField(
        label="Authentication Token",
        required=False,
        min_length=40,
        max_length=40,
        widget=forms.TextInput(attrs={
            'style': 'width: 333px; padding-left: 8px;'
            }),
    )


class ProcessGroupForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProcessGroupForm, self).__init__(*args, **kwargs)
        for field_name, field in list(self.fields.items()):
            field.widget.attrs['class'] = 'form-control'
        # if self.instance:
        # self.fields['belong_to'].queryset = Process_Group.objects.all()\
        # .exclude(id=self.instance.id)
        # self.fields['title'].label = gettext("Title")
        # self.fields['desc'].label = gettext("Description")

    class Meta:
        model = Process_Group
        fields = ('title', 'desc')


class AjaxProcessGroupForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        # pgs = kwargs.pop('pgs', None)
        super(AjaxProcessGroupForm, self).__init__(*args, **kwargs)
        # self.fields['title'].label = gettext("Title")
        # self.fields['desc'].label = gettext("Description")
        # self.fields['belong_to'].label = gettext("Belongs to")
        for field_name, field in list(self.fields.items()):
            field.widget.attrs['class'] = 'form-control'
        if self.instance:
            self.fields['belong_to'].queryset = Process_Group.objects \
                .exclude(id=self.instance.id)
        else:
            pgs = Process.objects.values_list('pg', flat=True)
            self.fields['belong_to'].queryset = Process_Group.objects \
                .filter(id__in=pgs)
        # if self.instance:
        # pgs = list(set(pgs) - set([self.instance.id]))
        # self.fields['belong_to'].queryset = Process_Group.objects\
        # .filter(id__in=pgs)
        # else:
        # self.fields['belong_to'].queryset = Process_Group.objects\
        # .filter(id__in=pgs)

    class Meta:
        model = Process_Group
        fields = ('title', 'desc', 'belong_to')


class AjaxProcessForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        # pgs = kwargs.pop('pgs', None)
        super(AjaxProcessForm, self).__init__(*args, **kwargs)
        for field_name, field in list(self.fields.items()):
            field.widget.attrs['class'] = 'form-control'
        # self.fields['pg'].queryset = Process_Group.objects\
        # .filter(id__in=pgs)

    class Meta:
        model = Process
        fields = ('title', 'ref_id', 'desc', 'owner')
        error_messages = {
            'ref_id': {
                'required': gettext("A reference is required!"),
            },
        }


class AjaxObjectiveForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        pg = kwargs.pop('pg', None)
        super(AjaxObjectiveForm, self).__init__(*args, **kwargs)
        # self.fields['title'].label = gettext("Title")
        # self.fields['ref_id'].label = gettext("Reference ID")
        # self.fields['desc'].label = gettext("Description")
        # self.fields['process'].label = gettext("Process")

        for field_name, field in list(self.fields.items()):
            field.widget.attrs['class'] = 'form-control'
        self.fields['process'].queryset = pg.process_group.all()

    class Meta:
        model = Objective
        fields = ('title', 'ref_id', 'desc', 'process')
        error_messages = {
            'ref_id': {
                'required': gettext("A reference is required!"),
            },
            'process': {
                'required': gettext("Please select a parent Process."),
            },
        }


class AjaxRiskForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        pg = kwargs.pop('pg', None)
        super(AjaxRiskForm, self).__init__(*args, **kwargs)
        # self.fields['title'].label = gettext("Title")
        # self.fields['ref_id'].label = gettext("Reference ID")
        # self.fields['desc'].label = gettext("Description")
        # self.fields['objective'].label = gettext("Objective")
        # self.fields['treatment'].label = gettext("Treatment")
        for field_name, field in list(self.fields.items()):
            field.widget.attrs['class'] = 'form-control'
        self.fields['objective'].queryset = pg.process_group_objective.all()

    class Meta:
        model = Risk
        fields = ('title', 'ref_id', 'desc', 'objective', 'treatment')
        error_messages = {
            'ref_id': {
                'required': gettext("A reference is required!"),
            },
            'objective': {
                'required': gettext("Please select a parent Objective."),
            },
        }


class AjaxControlForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        pg = kwargs.pop('pg', None)
        super(AjaxControlForm, self).__init__(*args, **kwargs)
        # self.fields['title'].label = gettext("Title")
        # self.fields['ref_id'].label = gettext("Reference ID")
        # self.fields['desc'].label = gettext("Description")
        # self.fields['control_type'].label = gettext("Control Type")
        # self.fields['risk'].label = gettext("Risk")
        # self.fields['owner'].label = gettext("Control Owner")
        # self.fields['control_class'].label = gettext("Control Class")
        # self.fields['frequency'].label = gettext("Frequency")

        for field_name, field in list(self.fields.items()):
            field.widget.attrs['class'] = 'form-control'
        self.fields['risk'].queryset = pg.process_group_risk.all()

    class Meta:
        model = Control
        fields = ('title', 'ref_id', 'desc', 'control_type', 'risk', 'owner',
                  'control_class', 'frequency')
        error_messages = {
            'ref_id': {
                'required': gettext("A reference is required!"),
            },
            'risk': {
                'required': gettext("Please select a parent Risk."),
            },
        }


class AjaxTestForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        pg = kwargs.pop('pg', None)
        super(AjaxTestForm, self).__init__(*args, **kwargs)
        # self.fields['title'].label = gettext("Title")
        # self.fields['ref_id'].label = gettext("Reference ID")
        # self.fields['desc'].label = gettext("Description")
        # self.fields['control'].label = gettext("Control")

        for field_name, field in list(self.fields.items()):
            field.widget.attrs['class'] = 'form-control'
        self.fields['control'].queryset = pg.process_group_control.all()

    class Meta:
        model = Test
        fields = ('title', 'ref_id', 'desc', 'control')
        error_messages = {
            'ref_id': {
                'required': gettext("A reference is required!"),
            },
            'control': {
                'required': gettext("Please select a parent Control."),
            },
        }

repository/views.py
# Create your views here.

repository/templates/repo/copy/childs.html
{% if object_list %}
    {% for obj in object_list %}
        <div class="panel {% if obj.class_name == 'process_group' %}panel-primary{% endif %}
                    {% if obj.class_name == 'process' %}panel-default{% endif %}
                    {% if obj.class_name == 'objective' %}panel-warning{% endif %}
                    {% if obj.class_name == 'risk' %}panel-danger{% endif %}
                    {% if obj.class_name == 'control' %}panel-info{% endif %}
                    {% if obj.class_name == 'test' %}panel-success{% endif %}" id="pnl_{{ generated_id }}_{{ obj.class_name }}_{{ obj.id }}">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <input class="ckbox" id="ck_{{ generated_id }}_{{ obj.class_name }}_{{ obj.id }}" type="checkbox" onclick="ckbox(this, '{{ obj.class_name }}', '{{ obj.id }}');">
                    {% if not obj.class_name == 'test' %}<a id="clk_{{ generated_id }}_{{ obj.class_name }}_{{ obj.id }}" data-toggle="collapse" data-parent="#acc_{{ generated_id }}" href="#{{ generated_id }}_{{ obj.class_name }}_{{ obj.id }}_collapse" onclick="get_childs('{{ generated_id }}_{{ obj.class_name }}_{{ obj.id }}', '{{ obj.class_name }}', '{{ obj.id }}')">+</a>{% endif %}
                    <a href="javascript:;" onclick="loadAjaxForm('{{ obj.class_name }}', '{{ obj.id }}')" class="{{ obj.class_name }}-{{ obj.id }}">{{ obj.title }}</a>
                </h4>
            </div>
            <div id="{{ generated_id }}_{{ obj.class_name }}_{{ obj.id }}_collapse" class="panel-collapse collapse">
                <div class="panel-body">
                    <div class="panel-group" id="acc_{{ generated_id }}_{{ obj.class_name }}_{{ obj.id }}">
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endif %}

repository/templates/repo/copy/repo_copy.html
{% extends "base.html" %}
{% load i18n %}
{% block page_title %}{% trans "Copy from the Repository" %}{% endblock %}
{% block content %}
    {% csrf_token %}
    <div id="page-wrapper">
        <br/>
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <div class="btn-group pull-right">
                                <a href="{% url 'audits:audit' audit_id %}" class="btn btn-info">{% trans "Back to audit" %}</a>
                            </div>
                            <h4>{% trans "Copy from the Repository" %}</h4>
                        </div>
                        <div class="panel-body">
                            <form method="post" action="{% url 'audits:repo_copy_view' audit_id %}">{% csrf_token %}
                                <div class="col-md-12">
                                    <div class="col-md-6">
                                        {% include 'repo/copy/childs.html' %}
                                        {% include "pagination.html" %}
                                        <input type="hidden" id="copy_object" name="copy_object">
                                        <input type="hidden" id="copy_source" name="copy_source">
                                        <input type="hidden" id="copy_parents" name="copy_parents">
                                        <input type="hidden" id="selected_id" name="selected_id">
                                        <button type="submit" class="btn btn-default btn-primary">{% trans "Copy" %}</button>
                                        <a href="{% url 'audits:audit' audit_id %}" class="btn btn-light">{% trans "Cancel" %}</a>
                                    </div>
                                    <div class="col-md-6" id="right_panel">
                                        <p>{% trans "Only one process will be copied at a time." %}</p>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script>
        function get_childs(gen_id, cls_name, obj_id) {
            $("#clk_" + gen_id).attr("onclick", "");
            var url = "/repository/process-group/{{ process_group_id }}/management/" + cls_name + "/" + obj_id + "/childs/?copy=true&generated_id=" + gen_id;
            $.ajax({
                url: url,
                type: "GET",
                dataType: "json",
                data: {management: true},
                success: function (result) {
                    $("#acc_" + gen_id).empty().append(result.html);
                }
            });
        }

        /*
        function ckbox(elm, obj, source, parents){
        cur_id = $(elm).attr("id");
        if($(elm).is(":checked")){
        $("#copy_object").val(obj);
        $("#copy_source").val(source);
        $("#copy_parents").val(parents);
        $("input:checkbox").not($(elm)).prop("checked", false);
        $(elm).parent().parent().parent().find("input:checkbox").prop("checked", true);
        arr = cur_id.split('_')
        arr_len = arr.length;
        if (arr_len >= 5){
        $("#"+arr.slice(0,3).join('_')).prop("checked", true);
        if (arr_len >= 7){
        $("#"+arr.slice(0,5).join('_')).prop("checked", true);
        if (arr_len >= 9){
        $("#"+arr.slice(0,7).join('_')).prop("checked", true);
        if (arr_len >= 11){
        $("#"+arr.slice(0,9).join('_')).prop("checked", true);
        if (arr_len >= 13){
        $("#"+arr.slice(0,11).join('_')).prop("checked", true);
        }
        }
        }
        }
        }
        }
        else{
        $("#copy_object").val('');
        $("#copy_source").val('');
        $("#copy_parents").val('');
        $("input:checkbox").prop("checked", false);
        }
        }
        */

        function ckbox(elm, source, obj) {
            cur_id = $(elm).attr("id");
            if ($(elm).is(":checked")) {
                $("input:checkbox").prop("checked", false);
                $(elm).prop("checked", true);
                $("#copy_object").val(obj);
                $("#copy_source").val(source);
                //$("#copy_parents").val(cur_id);
                $("#selected_id").val(cur_id);
                arr = cur_id.split('_')
                arr_len = arr.length;
                $(elm).parent().parent().parent().children().find(':checkbox').prop("checked", true);
                ckElm = elm;
                while (arr_len > 2) {
                    ckElm = $(ckElm).parent().parent().parent().parent().parent().parent().siblings().find(":checkbox").first();
                    console.log($(ckElm).parent().parent().parent().parent().parent().parent().siblings());
                    $(ckElm).prop("checked", true);
                    //ckElm = $(ckElm).parent();
                    arr_len -= 2;
                }
            } else {
                $("#copy_object").val('');
                $("#copy_source").val('');
                $("#copy_parents").val('');
                $("#selected_id").val('');
                $("input:checkbox").prop("checked", false);
            }
        }
    </script>
{% endblock %}