audits/urls.py
# from django.conf.urls import url
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from repository.views.base import RepoCopyView
from . import views
from .views import RepoCopy, AuditCopyPushRepo, AuditCopyView

urlpatterns = [
    path('', login_required(views.IndexView.as_view()), name='index'),
    path('create/', login_required(views.audit_create), name='audit_create'),
    path('audit/<int:audit_id>/copy-audit/', login_required(
        AuditCopyView.as_view()), name='audit_copy'),
    path('audit/<int:audit_id>/copy-repo/', login_required(
        RepoCopyView.as_view()), name='repo_copy'),
    path('audit/<int:audit_id>/copy-repos/', login_required(
        RepoCopy.as_view()), name='repo_copy_view'),
    path('audit/<int:audit_id>/push-repo/', login_required(
        AuditCopyPushRepo.as_view()), name='audit_push_repo'),

    path('audit/<int:audit_id>/', login_required(views.audit), name='audit'),
    path('not_implemented', login_required(views.not_implemented), name='not_implemented'),

    # path('audit/process/create/', login_required(views.process),
    #     name='process_create'),
    # path('audit/process/<int:process_id>/',
    #     login_required(views.process), name='audit_process'),
    # path('audit/objective/create/', login_required(views.objective),
    #     name='objective_create'),
    # path('audit/objective/<int:objective_id>/',
    #     login_required(views.objective), name='audit_objective'),
    # path('audit/risk/create/', login_required(views.risk), name='risk_create'),
    # path('audit/risk/<int:risk_id>/', login_required(views.risk),
    #     name='audit_risk'),
    # path('audit/<int:audit_id>/control/create/',
    #     login_required(views.control_create), name='control_create'),
    # path('audit/control/<int:control_id>/',
    #     login_required(views.control), name='audit_control'),

    path('audit/<int:audit_id>/execute/<str:view_type>', #process|objective|risk|control|test
        login_required(views.AuditExecuteView.as_view()), name='audit_execute'),
    path('audit/process/<int:process_id>/objective/', login_required(views.process_objective),
        name='audit_process_objective'),
    path('audit/objective/<int:objective_id>/risks/',
        login_required(views.objective_risk), name='audit_objective_risk'),
    path('audit/risk/<int:risk_id>/controller/',
        login_required(views.risk_controller), name='audit_risk_controller'),
    path('audit/control/<int:control_id>/test/',
        login_required(views.controller_test), name='audit_controller_test'),
    path('audit/test/<int:test_id>/findings/',
        login_required(views.test_findings), name='audit_test_findings'),
    path('audit/test/<int:test_id>/ajax/',
        login_required(views.AjaxTestResultView.as_view()),
        name='audit_ajax_test_form'),
    path('audit/finding/ajax-add/',
        login_required(views.AjaxFindingView.as_view()),
        name='ajax_finding_view'),
    path('attachment/<int:attachment_id>/delete/',
        login_required(views.AjaxAttachmentDeleteView.as_view()),
        name='ajax_attachment_delete'),
    path('audit/<int:audit_id>/management/', login_required(views.AuditChildView.as_view()),
        name='audit_management'),
    # Process Management
    path('audit/<int:audit_id>/process/add/', login_required(views.AjaxProcessAddEditView.as_view()),
        name='ajax_process_add'),
    path('audit/<int:audit_id>/process/<int:process_id>/edit/', login_required(views.AjaxProcessAddEditView.as_view()),
        name='ajax_process_edit'),
    path('process/<int:process_id>/delete/', login_required(views.AjaxProcessDeleteView.as_view()),
        name='ajax_process_delete'),
    # Objective Management
    path('audit/<int:audit_id>/objective/add/', login_required(views.AjaxObjectiveAddEditView.as_view()),
        name='ajax_objective_add'),
    path('audit/<int:audit_id>/objective/<int:objective_id>/edit/', login_required(views.AjaxObjectiveAddEditView.as_view()),
        name='ajax_process_edit'),
    path('objective/<int:objective_id>/delete/', views.AjaxObjectiveDeleteView.as_view(),
        name='ajax_objective_delete'),
    # Risk Management
    path('audit/<int:audit_id>/risk/add/', login_required(views.AjaxRiskAddEditView.as_view()),
        name='ajax_risk_add'),
    path('audit/<int:audit_id>/risk/<int:risk_id>/edit/', login_required(views.AjaxRiskAddEditView.as_view()),
        name='ajax_risk_edit'),
    path('risk/<int:risk_id>/delete/', login_required(views.AjaxRiskDeleteView.as_view()),
        name='ajax_risk_delete'),
    # Control Management
    path('audit/<int:audit_id>/control/add/', login_required(views.AjaxControlAddEditView.as_view()),
        name='ajax_control_add'),
    path('audit/<int:audit_id>/control/<int:control_id>/edit/', login_required(views.AjaxControlAddEditView.as_view()),
        name='ajax_control_edit'),
    path('control/<int:control_id>/delete/', login_required(views.AjaxControlDeleteView.as_view()),
        name='ajax_control_delete'),
    # Test Management
    path('audit/<int:audit_id>/test/add/', login_required(views.AjaxTestAddEditView.as_view()),
        name='ajax_test_add'),
    path('audit/<int:audit_id>/test/<int:test_id>/edit/', login_required(views.AjaxTestAddEditView.as_view()),
        name='ajax_test_edit'),
    path('test/<int:test_id>/delete/', login_required(views.AjaxTestDeleteView.as_view()),
        name='ajax_test_delete'),
    # Report Generation
    path('audit/<int:pk>/report/', login_required(views.AuditReport.as_view()),
        name='audit_report'),
]

envelop/urls.py
"""envelop URL Configuration

"""
from django.conf import settings
# from django.conf.urls import include, urls
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.views.generic import TemplateView
from django.views.static import serve

from audits.views import index, LoginView

admin.site.site_header = 'Envelop administration'
admin.AdminSite.site_title = 'Envelop'

urlpatterns = [
    path('', login_required(index), name='index'),
    path('login/', LoginView.as_view(), name='envelope_login'),
    path('not_implemented/', TemplateView.as_view(template_name="not_implemented.html")),
    path('audits/', include(('audits.urls', 'audits'), namespace="audits")),
    path('admin/', admin.site.urls),
    #    url(r'^files/', include('db_file_storage.urls')),
    path('planning/', include(('planning.urls', 'planning'), namespace='planning')),
    # url('help/', serve, {'document_root': settings.DOCS_ROOT, 'path': 'index.html'}),
    # url('help/(?P<path>.*)$', serve, {'document_root': settings.DOCS_ROOT}),
    path('repository/', include('repository.urls', "repo")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

planning/urls.py
# -*- coding: utf-8 -*-
# from django.conf.urls import url
from django.urls import path, include

from planning.views import PlanningView, PlanningAuditMonthView, PlanningDayView

urlpatterns = [
    path('', PlanningView.as_view(), name="planning_list"),
    path('day/', PlanningDayView.as_view(), name="planning_day"),
    path('audits/', PlanningAuditMonthView.as_view(), name="planning_audits"),
]

repository/urls.py
# from django.conf.urls import url
from django.urls import path
from django.contrib.auth.decorators import login_required
from enum import Enum

from repository.views.base import AjaxAttachmentDeleteView, AjaxChildsAddEditView, AjaxChildsDeleteView, ProcessGroupCreateView, ProcessGroupDetailView, ProcessGroupGetChilds, \
    ProcessGroupManagement, ReposIndexView
from repository.views.wipani import AjaxChildsDetailsView, AjaxWipaniDeleteView, AjaxWipaniPullView, AjaxWipaniPushView, TokenView, RegisterView, WipaniDetailsView, WipaniListView

app_name = "repo"

class ObjType1(Enum):
    PROCESS_GROUP = 'process_group'
    PROCESS = 'process'
    OBJECTIVE = 'objective'
    RISK = 'risk'
    CONTROL = 'control'
    TEST = 'test'

urlpatterns = [
    path('', login_required(ReposIndexView.as_view()), name='repo_index'),
    path('process-group/create/', login_required(ProcessGroupCreateView.as_view()), name='pg_create'),
    path('process-group/<int:process_group_id>/', login_required(ProcessGroupDetailView.as_view()), name='process_group'),
    path('process-group/<int:process_group_id>/management/', login_required(ProcessGroupManagement.as_view()),
        name='pg_management'),
    path('process-group/<int:process_group_id>/management/<str:ctype>process_group|process|objective|risk|control|test)/<int:object_id>/childs/',
        login_required(ProcessGroupGetChilds.as_view()), name='pg_childs'),
    path('process-group/<int:process_group_id>/management/<str:ctype>process_group|process|objective|risk|control|test)/add/',
        login_required(AjaxChildsAddEditView.as_view()), name='pg_childs_add'),
    path('process-group/<int:process_group_id>/management/<str:ctype>process_group|process|objective|risk|control|test)/<int:object_id>/edit/',
        login_required(AjaxChildsAddEditView.as_view()), name='pg_childs_edit'),
    path('process-group/<int:process_group_id>/management/<str:ctype>process_group|process|objective|risk|control|test)/<int:object_id>/delete/',
        login_required(AjaxChildsDeleteView.as_view()), name='pg_childs_delete'),

    path('attachment/<int:attachment_id>/delete/', login_required(AjaxAttachmentDeleteView.as_view()),
        name='ajax_attachment_delete'),

    path('wipani/register/', RegisterView.as_view(), name='WipaniRegister'),
    path('wipani/token/', TokenView.as_view(), name='WipaniToken'),
    path('wipani/list/', WipaniListView.as_view(), name='WipaniList'),
    path('wipani/list/<int:pk>/', WipaniDetailsView.as_view(), name='WipaniDetails'),
    path('wipani/list/<int:pk>/details/', AjaxChildsDetailsView.as_view(), name='AjaxChildsDetails'),
    path('wipani/list/<int:pk>/pull/', AjaxWipaniPullView.as_view(), name='AjaxWipaniPullView'),
    path('wipani/list/<int:pk>/delete/<str:name>/', AjaxWipaniDeleteView.as_view(), name='AjaxWipaniDeleteView'),
    path('process-group/<int:pk>/wipani/push/', AjaxWipaniPushView.as_view(), name='AjaxWipaniPush'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <title>{% block page_title %}{% endblock %} - Envelop (Community Version)</title>
    <!-- Latest compiled and minified CSS -->
    <!-- link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap-multiselect.css' %}" type="text/css"/>

    <!-- Optional theme -->
    <!-- link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" -->

    <!-- script src="https://code.jquery.com/jquery-1.11.3.min.js"></script -->
    <script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
    <!-- Latest compiled and minified JavaScript -->
    <!-- script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- script src="http://malsup.github.com/jquery.form.js"></script -->
    <script src="{% static 'js/jquery.form.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/bootstrap-multiselect.js' %}"></script>
    <script src="{% static 'js/common.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            UpdateSelectMultiple();
        });
        $(document).ajaxSuccess(function () {
            UpdateSelectMultiple();
        });
    </script>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block header_html %}
    {% endblock %}
</head>
<body>
{% block headernav %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Envelop</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li><a href="/not_implemented">Search</a></li>
                        <li><a href="{% url 'repo:WipaniList' %}">Wipani</a></li>
                        <li><a href="{% url 'audits:index' %}">Audits</a></li>
                        <li><a href="{% url 'planning:planning_list' %}">Planning</a></li>
                        <li><a href="{% url 'repo:repo_index' %}">Repository</a></li>
                        <li><a href="https://demo.grcenvelop.com/help/" target="_blank">Help</a></li>
                        <li><a href="{% url 'admin:logout' %}?next=/">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'admin:login' %}?next={{ request.path }}">Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

<div class="container-fluid">
    <div class="row">
        {% block content %}
        {% endblock %}
    </div>
</div>
<footer class="container-fluid text-center">
    <p>&copy; 2024 <a href="https://arambankudyil.com" target="_blank" title="Arambankudyil Consultancy">ACPL</a> ver 0.7.6</p>
</footer>

{% block script %}
{% endblock %}
</body>
</html>

templates/error-messages.html
<div class="row">
    <div class="msg-popup" style="margin-left: -15px">
        {% if messages %}
            {% for message in messages %}
                {% if 'success' in message.tags %}
                    <div class="alert alert-success alert-dismissable ">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        {{ message }}
                    </div>
                {% endif %}
                {% if 'error' in message.tags %}
                    <div class="alert alert-danger alert-dismissable ">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        {{ message }}
                    </div>
                {% endif %}
                {% if 'warning' in message.tags %}
                    <div class="alert alert-warning alert-dismissable ">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        {{ message }}
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
</div>

templates/messaging.html
{% load i18n %}
{% if messages %}
    {% for message in messages %}
        <div class="django_message alert {% if message.tags == 'success' %}alert-success{% endif %}{% if message.tags == 'error' %}alert-danger{% endif %} alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">×</span><span class="sr-only">{% trans "Close" %}</span>
            </button>
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/pagination.html
{% if is_paginated %}
    <nav class="pull-right col-md-8">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li>
                    <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% endif %}
            {% for page in page_obj.paginator.page_range %}
                <li class="{% if page_obj.number == page %}active{% endif %}"><a href="?page={{ page }}">{{ page }}</a></li>
            {% endfor %}
            {% if page_obj.has_next %}
                <li>
                    <a href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}