audits/urls.py
# from django.conf.urls import url
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from repository.views.base import RepoCopyView
from . import views
from .views import RepoCopy, AuditCopyPushRepo, AuditCopyView

urlpatterns = [
    path('', login_required(views.IndexView.as_view()), name='index'),
    path('create/', login_required(views.audit_create), name='audit_create'),
    path('audit/<int:audit_id>/copy-audit/', login_required(
        AuditCopyView.as_view()), name='audit_copy'),
    path('audit/<int:audit_id>/copy-repo/', login_required(
        RepoCopyView.as_view()), name='repo_copy'),
    path('audit/<int:audit_id>/copy-repos/', login_required(
        RepoCopy.as_view()), name='repo_copy_view'),
    path('audit/<int:audit_id>/push-repo/', login_required(
        AuditCopyPushRepo.as_view()), name='audit_push_repo'),

    path('audit/<int:audit_id>/', login_required(views.audit), name='audit'),
    path('not_implemented', login_required(views.not_implemented), name='not_implemented'),

    # path('audit/process/create/', login_required(views.process),
    #     name='process_create'),
    # path('audit/process/<int:process_id>/',
    #     login_required(views.process), name='audit_process'),
    # path('audit/objective/create/', login_required(views.objective),
    #     name='objective_create'),
    # path('audit/objective/<int:objective_id>/',
    #     login_required(views.objective), name='audit_objective'),
    # path('audit/risk/create/', login_required(views.risk), name='risk_create'),
    # path('audit/risk/<int:risk_id>/', login_required(views.risk),
    #     name='audit_risk'),
    # path('audit/<int:audit_id>/control/create/',
    #     login_required(views.control_create), name='control_create'),
    # path('audit/control/<int:control_id>/',
    #     login_required(views.control), name='audit_control'),

    path('audit/<int:audit_id>/execute/<str:view_type>', #process|objective|risk|control|test
        login_required(views.AuditExecuteView.as_view()), name='audit_execute'),
    path('audit/process/<int:process_id>/objective/', login_required(views.process_objective),
        name='audit_process_objective'),
    path('audit/objective/<int:objective_id>/risks/',
        login_required(views.objective_risk), name='audit_objective_risk'),
    path('audit/risk/<int:risk_id>/controller/',
        login_required(views.risk_controller), name='audit_risk_controller'),
    path('audit/control/<int:control_id>/test/',
        login_required(views.controller_test), name='audit_controller_test'),
    path('audit/test/<int:test_id>/findings/',
        login_required(views.test_findings), name='audit_test_findings'),
    path('audit/test/<int:test_id>/ajax/',
        login_required(views.AjaxTestResultView.as_view()),
        name='audit_ajax_test_form'),
    path('audit/finding/ajax-add/',
        login_required(views.AjaxFindingView.as_view()),
        name='ajax_finding_view'),
    path('attachment/<int:attachment_id>/delete/',
        login_required(views.AjaxAttachmentDeleteView.as_view()),
        name='ajax_attachment_delete'),
    path('audit/<int:audit_id>/management/', login_required(views.AuditChildView.as_view()),
        name='audit_management'),
    # Process Management
    path('audit/<int:audit_id>/process/add/', login_required(views.AjaxProcessAddEditView.as_view()),
        name='ajax_process_add'),
    path('audit/<int:audit_id>/process/<int:process_id>/edit/', login_required(views.AjaxProcessAddEditView.as_view()),
        name='ajax_process_edit'),
    path('process/<int:process_id>/delete/', login_required(views.AjaxProcessDeleteView.as_view()),
        name='ajax_process_delete'),
    # Objective Management
    path('audit/<int:audit_id>/objective/add/', login_required(views.AjaxObjectiveAddEditView.as_view()),
        name='ajax_objective_add'),
    path('audit/<int:audit_id>/objective/<int:objective_id>/edit/', login_required(views.AjaxObjectiveAddEditView.as_view()),
        name='ajax_process_edit'),
    path('objective/<int:objective_id>/delete/', views.AjaxObjectiveDeleteView.as_view(),
        name='ajax_objective_delete'),
    # Risk Management
    path('audit/<int:audit_id>/risk/add/', login_required(views.AjaxRiskAddEditView.as_view()),
        name='ajax_risk_add'),
    path('audit/<int:audit_id>/risk/<int:risk_id>/edit/', login_required(views.AjaxRiskAddEditView.as_view()),
        name='ajax_risk_edit'),
    path('risk/<int:risk_id>/delete/', login_required(views.AjaxRiskDeleteView.as_view()),
        name='ajax_risk_delete'),
    # Control Management
    path('audit/<int:audit_id>/control/add/', login_required(views.AjaxControlAddEditView.as_view()),
        name='ajax_control_add'),
    path('audit/<int:audit_id>/control/<int:control_id>/edit/', login_required(views.AjaxControlAddEditView.as_view()),
        name='ajax_control_edit'),
    path('control/<int:control_id>/delete/', login_required(views.AjaxControlDeleteView.as_view()),
        name='ajax_control_delete'),
    # Test Management
    path('audit/<int:audit_id>/test/add/', login_required(views.AjaxTestAddEditView.as_view()),
        name='ajax_test_add'),
    path('audit/<int:audit_id>/test/<int:test_id>/edit/', login_required(views.AjaxTestAddEditView.as_view()),
        name='ajax_test_edit'),
    path('test/<int:test_id>/delete/', login_required(views.AjaxTestDeleteView.as_view()),
        name='ajax_test_delete'),
    # Report Generation
    path('audit/<int:pk>/report/', login_required(views.AuditReport.as_view()),
        name='audit_report'),
]

envelop/urls.py
"""envelop URL Configuration

"""
from django.conf import settings
# from django.conf.urls import include, urls
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.views.generic import TemplateView
from django.views.static import serve

from audits.views import index, LoginView

admin.site.site_header = 'Envelop administration'
admin.AdminSite.site_title = 'Envelop'

urlpatterns = [
    path('', login_required(index), name='index'),
    path('login/', LoginView.as_view(), name='envelope_login'),
    path('not_implemented/', TemplateView.as_view(template_name="not_implemented.html")),
    path('audits/', include(('audits.urls', 'audits'), namespace="audits")),
    path('admin/', admin.site.urls),
    #    url(r'^files/', include('db_file_storage.urls')),
    path('planning/', include(('planning.urls', 'planning'), namespace='planning')),
    # url('help/', serve, {'document_root': settings.DOCS_ROOT, 'path': 'index.html'}),
    # url('help/(?P<path>.*)$', serve, {'document_root': settings.DOCS_ROOT}),
    path('repository/', include('repository.urls', "repo")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

audits/views.py
from datetime import date
from django.contrib import messages
from django.core.files import File
from django.forms import inlineformset_factory
from django.http import JsonResponse
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext
from django.views import generic
from django.views.decorators.csrf import csrf_exempt

from .forms import AuditForm, AjaxTestResultForm, AjaxFindingForm, \
    AjaxProcessForm, AjaxObjectiveForm, AjaxRiskForm, AjaxControlForm, \
    AjaxTestForm
from .models import Process, Objective, Risk, Control, Test, \
    Finding, Audit, Attachment

from repository.models import Process_Group, Process as RP, \
    Objective as RO, Risk as RR, Control as RC, Test as RT, Attachment as RAttachment


class IndexView(generic.ListView):
    template_name = 'audits/index.html'
    context_object_name = 'all_audits'

    def get_queryset(self):
        return Audit.objects.order_by('-start_date')[:10]

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        year = date.today().year - 2
        y = []
        x = []
        for i in range(3):
            a = Audit.objects.filter(fy=int(year) + i, status='AC').count()
            d = Audit.objects.filter(fy=int(year) + i, status='DR').count()
            c = Audit.objects.filter(fy=int(year) + i, status='CL').count()
            y.append([a, d, c])
            x.append(int(year) + i)
        context['x'] = x
        context['y'] = y
        return context


class LoginView(generic.TemplateView):
    template_name = 'login.html'

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        if 'next' in list(self.request.GET.keys()):
            context['next'] = self.request.GET['next']
        return context


def index(request):
    all_audits = Audit.objects.order_by('-start_date')[:10]
    context = {'all_audits': all_audits}
    year = date.today().year - 2
    y = []
    x = []
    for i in range(3):
        a = Audit.objects.filter(fy=int(year) + i, status='AC').count()
        b = Audit.objects.filter(fy=int(year) + i, status='DR').count()
        c = Audit.objects.filter(fy=int(year) + i, status='CL').count()
        y.append([a, b, c])
        x.append(int(year) + i)
    context['x'] = x
    context['y'] = y
    return render(request, 'audits/index.html', context)


def not_implemented(request):
    return render(request, 'not_implemented.html')


class AuditChildView(generic.ListView):
    template_name = 'audits/audit_childs.html'

    # paginate_by = 5

    def get_queryset(self):
        queryset = Process.objects.filter(audit_id=self.kwargs['audit_id'])
        return queryset

    def get_context_data(self, **kwargs):
        context = super(AuditChildView, self).get_context_data(**kwargs)
        context['type'] = 'process'
        context['audit_id'] = self.kwargs['audit_id']
        context['audit'] = Audit.objects.get(id=int(self.kwargs['audit_id']))
        context['management'] = True
        return context


def audit(request, audit_id):
    aud = get_object_or_404(Audit, pk=audit_id)
    if request.method == "POST":
        form = AuditForm(request.POST, request.FILES, instance=aud)

        if form.is_valid():
            audit = form.save(commit=False)
            audit.changed_by = request.user
            audit.changed_on = timezone.now()
            audit = form.save()
            messages.success(request, 'Audit information was saved')
            papers = request.FILES.getlist('papers')
            try:
                if papers:
                    Attachment.objects.bulk_create(
                        [Attachment(content_object=audit,
                                    workpaper=attachment, filename=attachment.name)
                         for attachment in papers])

                messages.success(request, 'Attachment saved')
            except:
                messages.error(request, 'Attachment NOT saved')
                pass

            if request.POST.get('add_from_repo') == "":
                messages.info(request, 'add from repo')
                return render(request, 'audits/not_implemented.html')

            elif request.POST.get('copy_from_audit') == "":
                messages.info(request, 'copy from audit')
                return HttpResponseRedirect(
                    reverse('audits:audit_copy', args=[audit.id]))

            elif request.POST.get('add_manually') == "":
                messages.info(request, 'You may now add processes')
                # messages.debug(request, "add manually debug")
                return HttpResponseRedirect(reverse('audits:audit_management',
                                                    args=[audit.id]))

            elif request.POST.get('delete') == "":
                aud.delete()
                messages.success(request, 'Audit deleted')
                # messages.debug(request, "add manually debug")
                return HttpResponseRedirect(reverse('audits:index'))

            else:
                return HttpResponseRedirect(reverse('audits:audit', args=(audit.id,)))
                # return render(request, "audits/audit.html", {'form': form})

        else:
            messages.error(request, 'Your audit was NOT saved')
            return render(request, "audits/audit.html", {'form': form})
    else:
        form = AuditForm(instance=aud)
        return render(request, "audits/audit.html", {'form': form})


def audit_create(request):
    if request.method == "POST":
        form = AuditForm(request.POST)
        if form.is_valid():
            audit = form.save(commit=False)
            audit.changed_by = request.user
            audit.changed_on = timezone.now()
            audit = form.save()
            messages.success(request, 'Audit was saved')
            papers = request.FILES.getlist('papers')
            try:
                if papers:
                    Attachment.objects.bulk_create(
                        [Attachment(content_object=audit,
                                    workpaper=attachment, filename=attachment.name)
                         for attachment in papers])
            except:
                pass

            if request.POST.get('add_from_repo') == "":
                messages.success(request, "add from Repo")
                # return render(request, "audits/add_from_repo.html",
                # {'form': form})
                return HttpResponseRedirect("audits/not_implemented")

            elif request.POST.get('add_manually') == "":
                messages.success(request, "add manually")
                return HttpResponseRedirect(reverse('audits:audit_management',
                                                    args=[audit.id]))

            else:
                messages.success(request, "Audit was created")
                return HttpResponseRedirect(reverse('audits:audit',
                                                    args=(audit.id,)))

        else:
            messages.error(request, 'Your audit was NOT saved')
            return render(request, "audits/audit.html", {'form': form})

    else:
        form = AuditForm()
        return render(request, "audits/audit.html", {'form': form})


def person_view(request, audit_id=None):
    if audit_id == None:
        audit = Audit()
    else:
        audit = Audit.objects.get(id=audit_id)

    ProcessFormSet = inlineformset_factory(Audit, Process, fields=('title',), can_delete=True)

    if request.method == "POST":
        auditform = AuditForm(request.POST, instance=audit)
        processformset = ProcessFormSet(request.POST, request.FILES, instance=audit)

        if auditform.is_valid() and processformset.is_valid():
            auditform.save()
            processformset.save()

            # Redirect to somewhere
            if '_save' in request.POST:
                return HttpResponseRedirect('/audits/audit/process/create')
            if '_addanother' in request.POST:
                return HttpResponseRedirect('/audits/audit/process/create')

    else:
        auditform = AuditForm(instance=audit)
        processformset = ProcessFormSet(instance=audit)

    return render('process2.html', {
        'auditform': auditform,
        'processformset': processformset,
    })


# @permission_required('audits.add_process', 'audits.change_process')
# def process(request, process_id=None):
#     if process_id != None:
#         pro = get_object_or_404(Process, pk=process_id)
#         if request.method == "POST":
#             form = ProcessForm(request.POST, instance=pro)
#             if form.is_valid():
#                 process = form.save(commit=False)
#                 process.changed_by = request.user
#                 process.changed_on = timezone.now()
#                 process = form.save()
#                 messages.success(request, 'Your process was saved')
#                 return HttpResponseRedirect(reverse('audits:audit_process', args=(process.id,)))
#             else:
#                 messages.error(request, 'Your process was NOT saved')
#                 return render(request, "audits/process.html", {'form': form})
#         else:
#             form = ProcessForm(instance=pro)
#             return render(request, "audits/process.html", {'form': form})
#     else:
#         if request.method == "POST":
#             form = ProcessForm(request.POST)
#             if form.is_valid():
#                 process = form.save(commit=False)
#                 process.changed_by = request.user
#                 process.changed_on = timezone.now()
#                 process = form.save()
#                 messages.success(request, 'Your process was saved')

audits/templates/audits/ajax_binding_process.html
<div class="panel panel-default">
    <div class="panel-heading">
        <h4 class="panel-title">
            <a id="process_{{ process.id }}" data-toggle="collapse" data-parent="#accordion1" href="#pr_{{ process.id }}_collapse" onclick="get_objectives('process_'+{{ process.id }}, {{ process.id }})">+
            </a><a href="javascript:void(0);" onclick="loadAjaxProcessForm({{ audit_id }}, {{ process.id }})" class="process-title-{{ process.id }}">{{ process.title }}</a>
        </h4>
    </div>
    <div id="pr_{{ process.id }}_collapse" class="panel-collapse collapse">
        <div class="panel-body">

            <div class="panel-group" id="acc_process_{{ process.id }}">
            </div>

        </div>
    </div>
</div>

audits/templates/audits/ajax_binding_risk.html
<div class="panel panel-warning risk-list-{{ obj.id }}">
    <div class="panel-heading">
        <h4 class="panel-title">
            <a id="pro_{{ process_id }}_obj_{{ objective_id }}_risk_{{ obj.id }}" data-toggle="collapse" data-parent="#acc_process_{{ process_id }}_obj_{{ objective_id }}" href="#pr_{{ process_id }}_obj_{{ objective_id }}_rs_{{ obj.id }}_collapse" onclick="get_controls('pro_'+{{ process_id }}+'_obj_'+{{ objective_id }}+'_risk_'+{{ obj.id }}, {{ obj.id }}, {{ process_id }}, {{ objective_id }})">+
            </a><a href="javascript:void(0);" onclick="loadAjaxRiskForm({{ obj.audit_id }}, {{ obj.id }})">{{ obj.title }}</a>
        </h4>
    </div>
    <div id="pr_{{ process_id }}_obj_{{ objective_id }}_rs_{{ obj.id }}_collapse" class="panel-collapse collapse">
        <div class="panel-body">
            <div class="panel-group" id="acc_pro_{{ process_id }}_obj_{{ objective_id }}_risk_{{ obj.id }}"></div>
        </div>
    </div>
</div>

audits/templates/audits/ajax_binding_test.html
<div class="panel panel-success test-list-{{ obj.id }}">
    <div class="panel-heading">
        <h4 class="panel-title">
            <a href="javascript:void(0);" onclick="loadAjaxTestForm({{ obj.audit_id }},{{ obj.id }});">{{ obj.title }}</a>
        </h4>
    </div>
</div>

audits/templates/audits/controller_tests.html
{% if tests %}
    {% for obj in tests %}
        <div class="panel panel-success test-list-{{ obj.id }}">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a id="pro_{{ process_id }}_obj_{{ objective_id }}_risk_{{ risk_id }}_ctrl_{{ control_id }}_test_{{ obj.id }}" data-toggle="collapse" data-parent="#acc_pro_{{ process_id }}_obj_{{ objective_id }}_risk_{{ risk_id }}_ctrl_{{ control_id }}" href="#pr_{{ process_id }}_obj_{{ objective_id }}_rs_{{ risk_id }}_ct_{{ control_id }}_test_{{ obj.id }}_collapse"
                       onclick="get_findings('pro_'+{{ process_id }}+'_obj_'+{{ objective_id }}+'_risk_'+{{ risk_id }}+'_ctrl_'+{{ control_id }}+'_test_'+{{ obj.id }}, {{ obj.id }}, {{ process_id }}, {{ objective_id }}, {{ risk_id }}, {{ control_id }})">+</a>
                    <a href="javascript:void(0);" onclick="loadAjaxTestForm({{ obj.id }});">{{ obj.title }}</a>
                </h4>
            </div>
            <div id="pr_{{ process_id }}_obj_{{ objective_id }}_rs_{{ risk_id }}_ct_{{ control_id }}_test_{{ obj.id }}_collapse" class="panel-collapse collapse">
                <div class="panel-body">
                    <div class="panel-group test_{{ obj.id }}" id="acc_pro_{{ process_id }}_obj_{{ objective_id }}_risk_{{ risk_id }}_ctrl_{{ control_id }}_test_{{ obj.id }}"></div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endif %}

audits/templates/audits/finding_form_ajax.html
<div class="modal-body">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Enter Finding Details</h4>
    </div>
    <br><br>
    <form class="form-horizontal" method="post" id="findForm" action="{% url 'audits:ajax_finding_view' %}?test_id={{ test_id }}">{% csrf_token %}
        <div class="form-group">
            <label class="col-sm-2 control-label">Title</label>
            <div class="col-sm-10">
                {{ form.title }}<p class="ajaxformerror" id="fnd_title_err"></p>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Description</label>
            <div class="col-sm-10">
                {{ form.desc }}
            </div>
        </div>
        <div class="form-group workPapers">
            <label for="exampleInputFile">Work Papers</label><br>
            <div class="col-md-10"><input type="file" class="form-control" name="papers"><br></div>
        </div>
        <button type="button" class="btn btn-info" onclick="attachPaper();">Attach 1 more</button>
        <hr/>
    </form>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" onclick="savefindForm();" class="btn btn-primary">Save</button>
    </div>
</div>

audits/templates/audits/index.html
{% extends "base.html" %}
{% load static %}
{% block page_title %}Audits List{% endblock %}
{% block header_html %}
    <!-- script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js"></script -->
    <script type="text/javascript" src="{% static "js/Chart.min.js" %}"></script>
{% endblock %}

{% block content %}

    {% csrf_token %}
    <div class="col-md-3 text-center">
        <a href="{% url 'audits:audit_create' %}" class="btn btn-info btn-lg">Create a new Audit</a> <br>
    </div>
    <div class="col-md-4">
        <h2>Audit List</h2>
        {% if all_audits %}
            <ul>
                {% for audit in all_audits %}
                    <li><a href="{% url 'audits:audit' audit.id %}"><h4>{{ audit.title }}</h4></a>
                {% endfor %}
            </ul>
        {% else %}
            <p>No audits are available.</p>
        {% endif %}
    </div>
    {#% if '/audits' in request.path %#}
    <div class="col-md-5">
        <canvas id="myChart" width="400" height="400"></canvas>
    </div>
    <script>
        var data = {
            labels: [{{ x.0 }}, {{ x.1 }}, {{ x.2 }}],
            datasets: [
                {
                    label: "My First dataset",
                    fillColor: "rgba(220,220,220,0.5)",
                    strokeColor: "rgba(220,220,220,0.8)",
                    highlightFill: "rgba(220,220,220,0.75)",
                    highlightStroke: "rgba(220,220,220,1)",
                    data: [{{ y.0.0 }}, {{ y.1.0 }}, {{ y.2.0 }}]
                },
                {
                    label: "My Second dataset",
                    fillColor: "rgba(151,187,205,0.5)",
                    strokeColor: "rgba(151,187,205,0.8)",
                    highlightFill: "rgba(151,187,205,0.75)",
                    highlightStroke: "rgba(151,187,205,1)",
                    data: [{{ y.0.1 }}, {{ y.1.1 }}, {{ y.2.1 }}]
                },
                {
                    label: "My Third dataset",
                    fillColor: "rgba(101,137,175,0.5)",
                    strokeColor: "rgba(101,137,175,0.8)",
                    highlightFill: "rgba(101,137,175,0.75)",
                    highlightStroke: "rgba(101,137,175,1)",
                    data: [{{ y.0.2 }}, {{ y.1.2 }}, {{ y.2.2 }}]
                }
            ]
        };
        var options = {
            //Boolean - Whether the scale should start at zero, or an order of magnitude down from the lowest value
            scaleBeginAtZero: true,

            //Boolean - Whether grid lines are shown across the chart
            scaleShowGridLines: true,

            //String - Colour of the grid lines
            scaleGridLineColor: "rgba(0,0,0,.05)",

            //Number - Width of the grid lines
            scaleGridLineWidth: 1,

            //Boolean - Whether to show horizontal lines (except X axis)
            scaleShowHorizontalLines: true,

            //Boolean - Whether to show vertical lines (except Y axis)
            scaleShowVerticalLines: true,

            //Boolean - If there is a stroke on each bar
            barShowStroke: true,

            //Number - Pixel width of the bar stroke
            barStrokeWidth: 2,

            //Number - Spacing between each of the X value sets
            barValueSpacing: 5,

            //Number - Spacing between data sets within X values
            barDatasetSpacing: 1,

        }
        var ctx = document.getElementById("myChart").getContext("2d");
        var myBarChart = new Chart(ctx).Bar(data, options);
    </script>
    {#% endif %#}
{% endblock %}

audits/templates/audits/objective.html
{% extends "base.html" %}

{% block content %}
    <h2>Objective</h2>

    <form method="POST" class="post-form">
        {% csrf_token %}
        {% if messages %}
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        {% endif %}

        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
        <br>
        <a href="{% url 'audits:objective_create' %}">Create another Objective</a> | <a href="{% url 'audits:risk_create' %}">Create a Risk</a>
    </form>
{% endblock %}

audits/templates/audits/objective_execute.html
{% if object_list %}

    <div class="col-md-6">


        <div class="panel-group" id="accordion1">
            {% for obj in object_list %}
                <div class="modal fade" id="md_pr_{{ process_id }}_obj_{{ obj.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <h4 class="modal-title">{{ obj.title }}</h4>
                            </div>
                            <div class="modal-body">
                                {{ obj.ref_id }}
                            </div>
                            <div class="modal-body">
                                {{ obj.desc }}
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="panel panel-warning">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a id="pro_{{ process_id }}_obj_{{ obj.id }}" data-toggle="collapse" data-parent="#accordion1" href="#pr_{{ process_id }}_obj_{{ obj.id }}_collapse" onclick="get_risks('pro_'+{{ process_id }}+'_obj_'+{{ obj.id }}, {{ obj.id }}, {{ process_id }})">+
                            </a><a href="javascript:void(0);" data-toggle="modal" data-target="#md_pr_{{ process_id }}_obj_{{ obj.id }}">{{ obj.title }}</a>
                        </h4>
                    </div>
                    <div id="pr_{{ process_id }}_obj_{{ obj.id }}_collapse" class="panel-collapse collapse">
                        <div class="panel-body">
                            <div class="panel-group" id="acc_pro_{{ process_id }}_obj_{{ obj.id }}"></div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <div>Total: {{ object_list.count }} objectives</div>
    </div>
{% else %}
    <p>No objectives are available.</p>
{% endif %}

audits/templates/audits/right_panel_test_result.html
<h3 class="text-center">Test</h3>
<form class="form-horizontal" method="post" id="testForm">
    <div style='display:none'><input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token_value }}"/></div>
    <div class="form-group">
        <label class="col-sm-12"><span class="col-sm-2">Title</span> <span class="col-sm-10">{{ form.instance.title }}</span></label>
    </div>
    <div class="form-group">
        <label class="col-sm-12"><span class="col-sm-2">Reference</span> <span class="col-sm-10">{{ form.instance.ref_id }}</span></label>
    </div>
    <div class="form-group">
        <label class="col-sm-12"><span class="col-sm-2">Description</span> <span class="col-sm-10">{{ form.instance.desc }}</span></label>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Result</label>
        <div class="col-sm-10">{{ form.result }}</div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Result Description</label>
        <div class="col-sm-10">
            {{ form.result_desc }}<p class="ajaxformerror" id="res_desc_err"></p>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="button" class="btn btn-default" onclick="saveAjaxTestForm({{ test_id }});">Save</button>
            <a href="{% url 'audits:ajax_finding_view' %}?test_id={{ test_id }}" class="btn btn-default" data-toggle="modal" data-target="#createFinding">Create Finding</a>
        </div>
    </div>
</form>

<div class="modal fade" id="createFinding" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

        </div>
    </div>
</div>

<script>
    $(function () {
        $("a[data-target=#createFinding]").click(function (ev) {
            ev.preventDefault();
            target = $(this).attr("href");
            // load the url and show modal on success
            $("#createFinding .modal-body").load(target, function () {
                $("#createFinding").modal("show");
            });
        });
    });
</script>